# Generated by Django 3.2.4 on 2021-07-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troad', models.CharField(max_length=10, verbose_name='Титул дороги')),
                ('nroad', models.CharField(max_length=250, verbose_name='Тиутльное наименование дороги')),
                ('n_km', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Начало участка')),
                ('k_km', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Конец участка')),
            ],
        ),
    ]
